flags: {}
extra-package-dbs: []
nix:
  enable: false
  shell-file: shell.nix
packages:
- .
extra-deps:
- happy-1.19.9
- language-javascript-0.7.0.0
- git: git@github.com:kl0tl/purescript.git
  commit: 3fdbd6dc4e29c252d693e44657917850b99a815f
  subdirs:
    - '.'
    - lib/purescript-ast
    - lib/purescript-cst
- network-3.0.1.1
- these-1.0.1
- semialign-1
resolver: lts-13.26
flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
    quickcheck: false
